version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
    driver: bridge