exports.seed = async function (knex) {
  await knex("ingredients").del();

  await knex("ingredients").insert([
    {
      id: 1,
      name: "Kecap Manis",
      unit: "sdm",
      unit_purchase: "botol",
      minimum_purchase: 1,
      comparison_scale: 100,
      image_url: "https://example.com/kecap.jpg",
    },
    {
      id: 2,
      name: "Telur",
      unit: "butir",
      unit_purchase: "butir",
      minimum_purchase: 1,
      comparison_scale: 1,
      image_url: "https://example.com/telur.jpg",
    },
    {
      id: 3,
      name: "Nasi Putih",
      unit: "piring",
      unit_purchase: "piring",
      minimum_purchase: 1,
      comparison_scale: 1,
      image_url: "https://example.com/nasi.jpg",
    },
    {
      id: 4,
      name: "Bawang Merah",
      unit: "siung",
      unit_purchase: "siung",
      minimum_purchase: 1,
      comparison_scale: 1,
      image_url: "https://example.com/bawang_merah.jpg",
    },
    {
      id: 5,
      name: "Minyak Goreng",
      unit: "sdm",
      unit_purchase: "sdm",
      minimum_purchase: 1,
      comparison_scale: 1,
      image_url: "https://example.com/minyak.jpg",
    },
    {
      id: 6,
      name: "Mie Instan",
      unit: "bungkus",
      unit_purchase: "bungkus",
      minimum_purchase: 1,
      comparison_scale: 1,
      image_url: "https://example.com/mie.jpg",
    },
    {
      id: 7,
      name: "Cabe Merah",
      unit: "buah",
      unit_purchase: "buah",
      minimum_purchase: 1,
      comparison_scale: 1,
      image_url: "https://example.com/cabe.jpg",
    },
    {
      id: 8,
      name: "Sosis",
      unit: "buah",
      unit_purchase: "buah",
      minimum_purchase: 1,
      comparison_scale: 1,
      image_url: "https://example.com/sosis.jpg",
    },
  ]);
};
